# Generated by Django 4.1.2 on 2022-10-17 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='done',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
